# =========================================================
#                      每日清体力计划
# =========================================================
#
# 可以在这个文件中计划每天清体力具体要刷哪个副本
# 当天的计划会覆盖掉 config.yaml 中清体力的配置
# 
# 计划格式如下：
# ```
# YYYY-MM-DD:
#     副本类型: 副本名称
# ```
#
# 怕自己的计划写不对导致脚本出错？可以运行 `python schedule_checker.py` 来检查
#

1970-1-14:
    拟造花萼（金）: 回忆之蕾
1970-1-15:
    拟造花萼（赤）: 鳞渊境
1970-1-16:
    凝滞虚影: 空海之形
1970-1-17:
    侵蚀隧洞: 霜风之径
1970-1-18:
    饰品提取: 月下朱殷
1970-1-19:
    历战余响: 晨昏的回眸 
    侵蚀隧洞: 迷识之径    # 历战余响清不完一天的体力，可以把剩下的体力用来刷别的副本